# Generated by Django 6.0.7 on 2026-07-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='concentration',
            field=models.CharField(default='Eau De Parfum', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='longevity',
            field=models.CharField(default='8 - 10 Hours', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='story',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
